### PR TITLE
refactor: change order and basket system

### PR DESCRIPTION
**Pull request by tahapek5454**
+ changed order response
+ changed basket response
+ changed order service
+ changed basket service
+ added default product image to wwwroot

### CODE REVIEW

**Review by eemirhannk — DISMISSED** [review]
Amazing !

**Review by alperenkolat — DISMISSED** [review]
Okay

**Review by eemirhannk — APPROVED** [review]
Great !

**Review by alperenkolat — APPROVED** [review]
Okay

**Pull request merged**
