### PR TITLE
feat: add categories controller

### PR DESCRIPTION
**Pull request by tahapek5454**
+ designed repository for all conditional request
+ added all endpoint for category

### CODE REVIEW

**Review by alperenkolat — DISMISSED** [review]
Okay

**Comment by tahapek5454** [comment]
+ added product controller
+ added product service
+ added dto relating to product 
+ added new migration to fit design

**Review by alperenkolat — APPROVED** [review]
okay

**Review by eemirhannk — APPROVED** [review]
Cool

**Pull request merged**
