### PR TITLE
build: build onion arc

### PR DESCRIPTION
**Pull request by tahapek5454**
We create architecture

### CODE REVIEW

**Comment by alperenkolat** [comment]
We create architecture; okay

**Review by MelihSelamiUrkmezz — APPROVED** [review]
Ok!

**Comment by MelihSelamiUrkmezz** [comment]
> We create architecture; okay

You can approve this pr!

**Review by eemirhannk — APPROVED** [review]
okay,its good

**Review by eemirhannk — APPROVED** [review]
nice

**Pull request closed without merging**
